version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.4

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.9.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: | 
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git config --global user.password $GH_TOKEN
            yarn upload
      - run:
          name: Publish docs
          command: yarn docs
  
workflows:
  version: 2
  build_test_publish:
    jobs:
      - build
      - test:
          requires:
              - build
      - publish:
          filters:
            branches:
              only: master

